apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: archive
            image: curlimages/curl:7.78.0
            command:
            - sh
            - -c
            - |
              curl http://custom-app-service/logs > /tmp/app.log
              tar -czf /tmp/app-logs-$(date +%s).tar.gz /tmp/app.log
          restartPolicy: OnFailure
