apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: app
        image: custom-app:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: config
          mountPath: /app/config
      volumes:
      - name: logs
        hostPath:
          path: /var/log/custom-app
          type: DirectoryOrCreate
      - name: config
        configMap:
          name: app-config
