apiVersion: v1
kind: Pod
metadata:
  name: custom-app-pod
spec:
  containers:
  - name: app
    image: custom-app:latest
    volumeMounts:
    - name: logs
      mountPath: /app/logs
    - name: config
      mountPath: /app/config
  volumes:
  - name: logs
    emptyDir: {}
  - name: config
    configMap:
      name: app-config
